config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcomes#index'

  get 'about', to: 'welcomes#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 5, maximum: 100}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: {sensitive: false}, length: { minimum: 3, maximum: 10 }

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 105},
            uniqueness: {case_sensitive: false},
            format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.

# For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception


  helper_method :current_user, :logged_in?

  def current_user
     (@current_user || User.find(session[:user_id]) if session[:user_id])

    # return the user if there is a user_id stored & backed by the browser in the session hash
    # if so then find the user in the db based on the user id
    # current_user if the current user already exist, if so return the previous current user
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  def new
    @article = Article.new #instance variable
  end

  def create
    @article = Article.new(article_params)
    # @article.user = User.first
    @article.user = current_user  #assign the current user to the user's attributes
    if @article.save
      flash[:notice] = "article was sucessfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "article was sucessfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfuly deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)

    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id #setting the sessions hash user_id, which is backed by user browser
      flash[:success] = "You have sucessfully logged In"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] =  "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users =  User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        flash[:success] = "Welcome to the Alpha blog #{@user.username}"
        redirect_to user_path(@user)
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated sucessfully"
      redirect_to user_path(@user)
    else
      render 'edit'
    end

  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user has been deleted"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You can only edit your own account"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin users can perform that action"
        redirect_to root_path
      end
    end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url =  "https://www.secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag("cat.jpg", alt: user.username)
  end
end

app/views/articles/_article.html.erb
<h1 align="center">Listing all articles</h1>
<% articles.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions">
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete,
                      data: { confirm: "Are you sure you want to delete the article?"},
                      class: "btn btn-xs btn-danger" %>
        </div>
          <br>
          <p> Created by <%= article.user.username %>

          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render './shared/errors', obj: @article %>
<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>

    <% end %>

    <div class="col-xs-4 col-xs-offset-4">

      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]

    </div>

  </div>

</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>a
<h1 align="center">Create new article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<div class="center">
  <%= will_paginate @articles%>
</div>
<%= render partial: 'article', object: @articles, as: :articles%>

<div class="center">
  <%= will_paginate @articles%>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<% if @article.user %>
  <ul class="listing" style="text-align: center; list-style: none;">
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user)%></li>
    <!--    link to the user showpage use user_path-->
    <li style="font-size:2em; padding:10px; font-weight: bold;"><%= link_to @article.user.username, user_path(@article.user)%> </li>
    <li><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></li>
  </ul>
<% end %>

<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete,
                  data: {confirm: "Are you sure you want to delete the article?"},
                  class: "btn btn-xs btn-danger" %>
      <%end%>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">

  <footer class="footer">

    <small>

      Copyright © 2018-2019

      by <a href="https://www.linkedin.com/in/huy-vu-a58414149">Huy Vu</a>

    </small>

    <nav>

      <ul>

        <li><%= link_to "About", about_path %></li>

      </ul>

    </nav>

  </footer>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Article", new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <%	 end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user)%></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The following errors prevent the article from getting created</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<% if obj.errors.any? %>

  <div class="row">

    <div class="col-xs-8 col-xs-offset-2">

      <div class="panel panel-danger">

        <div class="panel-heading">

          <h2 class="panel-title">

            <%= pluralize(obj.errors.count, "error") %>

            prohibited this article from being saved:

          </h2>

          <div class="panel-body">

            <ul>

              <% obj.errors.full_messages.each do |msg| %>

                <li><%= msg %></li>

              <% end %>

            </ul>

          </div>

        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render './shared/errors', obj: @user %>


<%= form_for @user do |f| %>
  <p>
    <%=	 f.label :username %><br>
    <%=	 f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? "Signup" : "Update Account") %>
  </p>
<% end %>

<%= link_to "Back to listing", articles_path%>

app/views/users/edit.html.haml
%h1 Edit your account
= render 'form', {link_descript: "Back to listing"}

app/views/users/index.html.haml
%h1{:align => "center"} All Alpha Bloggers
%div{:align => "center"}= will_paginate
%div{:align => "center"}
  -@users.each do |user|
    .row
      %ul{style: "list-style: none"}
        .listing.col-md-4.col-md-offset-4.article-body.well.well-lg
          %li= link_to gravatar_for(user), user_path(user)
          -# link to the user showpage use user_path
          .article-title
            %li= link_to user.username, user_path(user)
          %li= pluralize(user.articles.count, "article") if user.articles
          - if logged_in? and current_user.admin?
            %li= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?"}
%div{:align=>"center"}=will_paginate

app/views/users/new.html.haml
%h1 Create a New User
= render './shared/errors', obj: @user
= render 'form'

app/views/users/show.html.haml
%h1
  .center Welcome to #{@user.username}'s page
.center
  = will_paginate @user_articles
.center
  = gravatar_for @user
%h4{style: "text-align: center;"} #{@user.username}'s article
= render partial: 'articles/article', object: @user_articles, as: :articles
%div{align: "center"}= will_paginate @user_articles

app/views/welcomes/about.html.erb
<h1>This is a little project that models a database</h1>
<p>In this project you can add, delete, and update items</p>

app/views/welcomes/index.html.haml
.center.jumbotron
  %h1 ALPHA BLOG
  = link_to "Sign up now", signup_path, class: "btn btn-danger btn-lg btn-xlarge"